/** Flat [x0, z0, x1, z1, ...] coordinate list in local metres (+X east, +Z south). */
export type Coords = number[];

export interface MapBuilding {
  o: Coords;
  h?: Coords[];
  lv?: number;
  /** building:min_level (parts raised above the ground). */
  mlv?: number;
  ht?: number;
  /** Outline whose volume is drawn through its building:parts. */
  hp?: 1;
  /** This is a building:part. */
  part?: 1;
  /** Hidden wall indices (walls shared with an equal or taller part). */
  hid?: number[];
  t: 'house' | 'block' | 'industrial' | 'small' | 'church' | 'tower' | 'torre' | 'townhall' | 'station' | 'canopy' | 'ruins' | 'greenhouse';
  n?: string;
  mat?: string;
  /** Ground under the walls (local y, from the terrain model). */
  gy?: number;
  /** Measured by LiDAR (local y): roof top and eaves. */
  top?: number;
  eave?: number;
  /** "lidar" for buildings traced from the point cloud (missing in OSM). */
  src?: 'lidar';
}

export interface MapArea {
  k: string;
  o: Coords;
  h?: Coords[];
  n?: string;
  /** Pitches: sport (soccer, tennis, pelota, skittles…); parkings: bay orientation. */
  s?: string;
  /** Pitches: covered. */
  c?: 1;
  /** Woods: needle-leaved (n) or broad-leaved (b). */
  l?: 'n' | 'b';
  /** Water areas: surface level (local y). */
  wl?: number;
}

/** Shop, bar or public service, on the street-facing wall of its building. */
export interface MapShop {
  /** Point on the wall. */
  x: number;
  z: number;
  /** Heading of the wall's outward normal (rotation.y mapping +Z onto it). */
  a: number;
  /** Front width (m). */
  w: number;
  c:
    | 'bar'
    | 'food'
    | 'cafe'
    | 'bank'
    | 'pharmacy'
    | 'police'
    | 'health'
    | 'civic'
    | 'grocery'
    | 'beauty'
    | 'garage'
    | 'shop'
    | 'office'
    | 'hotel';
  /** Sign text (real name, or the trade in Spanish). */
  n: string;
}

export interface MapRoad {
  p: Coords;
  k: string;
  w: number;
  n?: string;
  /** Bridge. */
  b?: 1;
  /** Sidewalks: 1 left, 2 right, 3 both. */
  sw?: number;
  /** Indices of junction vertices. */
  j?: number[];
}

export interface MapPoi {
  k: 'townhall' | 'locomotive' | 'belltower' | 'statue' | 'bandstand' | 'fountain' | 'drinking_water' | 'fuel' | 'bus_stop';
  n?: string;
  x: number;
  z: number;
  o?: Coords;
  ht?: number;
}

export interface MapData {
  meta: {
    source: string;
    origin: { lat: number; lon: number; note: string };
    bounds: { minX: number; maxX: number; minZ: number; maxZ: number };
    utmOrigin?: { E: number; N: number };
    /** Heightmap file baked from LiDAR + MDT (tools/geodata). */
    terrain?: { file: string; cols: number; rows: number; cell: number; minX: number; minZ: number; scale: number; datum: number };
    /** Orthophoto tiles (tools/geodata/fetch_ortho.py). */
    ortho?: { dir: string; tile: number; nx: number; nz: number; minX: number; minZ: number; source: string };
    sources?: string[];
    /** Real relief and imagery around the map (MDT25 + PNOA), drawn as the horizon. */
    surroundings?: {
      file: string;
      image: string;
      cols: number;
      rows: number;
      cell: number;
      minX: number;
      minZ: number;
      scale: number;
      imageBounds: [number, number, number, number];
    };
  };
  /** URL of the folder the map was loaded from (its side files live there). */
  baseUrl?: string;
  /** Heights of the surroundings grid (local y). */
  surroundings?: Float32Array;
  /** Ground heights (local y) on the meta.terrain grid; absent = flat map. */
  heights?: Float32Array;
  buildings: MapBuilding[];
  areas: MapArea[];
  roads: MapRoad[];
  rails: { p: Coords }[];
  /** `wl`: water surface (local y) at each vertex. */
  rivers: { p: Coords; w: number; n?: string; wl?: number[] }[];
  streams: { p: Coords; w: number }[];
  weirs: { p: Coords; n?: string }[];
  /** Flat [x, z, ...]. */
  trees: number[];
  /** Trees found in the LiDAR canopy: flat [x, z, height, crown radius, ...] (metres). */
  ltrees?: number[];
  /** Conifers (leaf_type=needleleaved), flat [x, z, ...]. */
  pines: number[];
  lamps: number[];
  benches: number[];
  /** Flat [x, z, angle, ...]. */
  crossings: number[];
  pois: MapPoi[];
  shops: MapShop[];
  /** Flat [x, z, angle, stone(0|1), ...]. */
  tables: number[];
  /** Flat [x, z, ...]. */
  playgrounds: number[];
}

const ARRAYS = [
  'buildings',
  'areas',
  'roads',
  'rails',
  'rivers',
  'streams',
  'weirs',
  'trees',
  'pines',
  'lamps',
  'benches',
  'crossings',
  'pois',
  'shops',
  'tables',
  'playgrounds',
] as const;

/**
 * Checks the shape of a map file (generated by scripts/osm-to-map.ts) before
 * the world is built from it; a stale or truncated file fails here, loudly.
 */
export function parseMap(raw: unknown, source = 'map'): MapData {
  const m = raw as Partial<MapData> | null;
  const b = m?.meta?.bounds;
  if (!b || ![b.minX, b.maxX, b.minZ, b.maxZ].every(Number.isFinite) || b.minX >= b.maxX || b.minZ >= b.maxZ) {
    throw new Error(`${source}: missing or invalid meta.bounds`);
  }
  for (const k of ARRAYS) if (!Array.isArray(m[k])) throw new Error(`${source}: "${k}" must be an array`);
  return m as MapData;
}

/** Decodes the Int16 heightmap (cm) that tools/geodata writes next to the map. */
export function decodeHeights(map: MapData, buffer: ArrayBuffer): Float32Array {
  const t = map.meta.terrain;
  if (!t) throw new Error('map has no meta.terrain');
  const raw = new Int16Array(buffer);
  if (raw.length !== t.cols * t.rows) throw new Error(`${t.file}: expected ${t.cols * t.rows} samples, got ${raw.length}`);
  const out = new Float32Array(raw.length);
  for (let i = 0; i < raw.length; i++) out[i] = raw[i] * t.scale;
  return out;
}

/** Fetches and validates a map file served from public/maps/, with its heightmap. */
export async function loadMap(url: string): Promise<MapData> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  const map = parseMap(await res.json(), url);
  map.baseUrl = new URL('.', new URL(url, location.href)).href;
  if (map.meta.terrain) {
    const hurl = new URL(map.meta.terrain.file, new URL(url, location.href)).href;
    const hr = await fetch(hurl);
    if (!hr.ok) throw new Error(`${hurl}: HTTP ${hr.status}`);
    map.heights = decodeHeights(map, await hr.arrayBuffer());
  }
  const s = map.meta.surroundings;
  if (s) {
    const sr = await fetch(new URL(s.file, map.baseUrl).href);
    if (sr.ok) {
      const raw = new Int16Array(await sr.arrayBuffer());
      map.surroundings = Float32Array.from(raw, (v) => v * s.scale);
    }
  }
  return map;
}
